eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        #defaultZone: http://localhost:8085/eureka
      defaultZone: http://localhost:8085/eureka/
        #defaultZone: ${EUREKA_URI:http://localhost}:8085/eureka
        #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
